### ISSUE TITLE
game always fails to start because of error

### ISSUE THREAD

**Issue by pokemonfan6498** [masagrator/SPRB-ENX#3] opened 2023-04-12 02:12 UTC
i got update for english translation but when i try to launch it it always shows error screen with text software closed because an error occured

**Comment by masagrator** [comment] 2023-04-12 04:35
For starters what is your version of game

**Comment by Squall-Leonhart** [comment] 2023-07-02 06:33
This mod is possibly faulty as it changes the game title id to the one for Portal 2.

**Comment by masagrator** [comment] 2023-07-02 07:14
> This mod is possibly made incorrectly as it changes the game title id to the one for Portal 2, not likely an issue for running on actual hardware, but definitely a problem for emulation.

Fixed

**Comment by Squall-Leonhart** [comment] 2023-07-02 07:36
Fast fix, thanks.

**Comment by learnmlcolab** [comment] 2023-07-02 11:15
@masagrator @Squall-Leonhart  I can confirm that the new update fixes https://github.com/yuzu-emu/yuzu/issues/10982 for me. Thanks for the quick fix.

**Comment by masagrator** [comment] 2023-07-10 07:46
Since OP didn't answer, I'm closing this issue.

**Closed by masagrator** 2023-07-10 07:46 UTC
